//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hearts_of_Gold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation_Catagories
    {
        public Donation_Catagories()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int CatagoryID { get; set; }
        public string Catagories { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
