//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hearts_of_Gold.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Donation_Location
    {
        public Donation_Location()
        {
            this.Requests = new HashSet<Request>();
            this.Items = new HashSet<Item>();
        }

        public int LocationID { get; set; }
        public string BusinessName { get; set; }
        public string Address { get; set; }

        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
