
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.ComponentModel.DataAnnotations;

namespace Hearts_of_Gold.Models
{

    using System;
    using System.Collections.Generic;
    [MetadataType(typeof(CategoryMetadata))]
    public partial class Donation_Categories
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donation_Categories()
        {

            this.Items = new HashSet<Item>();

        }


        public int CategoryID { get; set; }

        public string Categories { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<Item> Items { get; set; }

    }

}
