
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.ComponentModel.DataAnnotations;

namespace Hearts_of_Gold.Models
{

    using System;
    using System.Collections.Generic;
    [MetadataType(typeof(LocationMetadata))]
    public partial class Donation_Location
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donation_Location()
        {

            this.Requests = new HashSet<Request>();

            this.Items = new HashSet<Item>();

        }


        public int LocationID { get; set; }

        public string BusinessName { get; set; }

        public string Address { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<Request> Requests { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<Item> Items { get; set; }

    }

}
