
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hearts_of_Gold.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Donation_Categories
{

    public Donation_Categories()
    {

        this.Items = new HashSet<Item>();

    }


    public int CategoryID { get; set; }

    public string Categories { get; set; }



    public virtual ICollection<Item> Items { get; set; }

}

}
