//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Hearts_of_Gold.Models
{
    using System;
    using System.Collections.Generic;

    [Bind(Exclude = "ItemID")]
    public partial class Item
    {
        public Item()
        {
            this.Requests = new HashSet<Request>();
        }
        [ScaffoldColumn(false)]
        public int ItemID { get; set; }
        
        [DisplayName("Category")]
        public int CategoryID { get; set; }
        
        [DisplayName("Location")]
        public int LocationID { get; set; }

        
        [HiddenInput(DisplayValue = false)]
        public int UserID { get; set; }

        [DisplayName("Item")]
        [Required(ErrorMessage = "You must select an item")]
        public string Item1 { get; set; }

        [Required]
        [DisplayName("Item Quanity")]
        [Range(1, int.MaxValue, ErrorMessage = "You must enter a Quanity")]
        public int Quantity { get; set; }

        public string Description { get; set; }

        [ScaffoldColumn(true)]
        [Required(ErrorMessage = "You must select a Donation Category")]
        public virtual Donation_Categories Donation_Categories { get; set; }

        [ScaffoldColumn(true)]
        [Required(ErrorMessage = "You select a Donation Location")]
        public virtual Donation_Location Donation_Location { get; set; }

        //[ScaffoldColumn(false)]
        public virtual ICollection<Request> Requests { get; set; }

        //[ScaffoldColumn(false)]
        public virtual User User { get; set; }
    }
}