//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Hearts_of_Gold.Models
{
    using System;
    using System.Collections.Generic;
    
    [Bind(Exclude = "UserID")]
    public partial class User
    {
        public User()
        {
            this.Items = new HashSet<Item>();
            this.Requests = new HashSet<Request>();
        }
        [ScaffoldColumn(false)]
        public int UserID { get; set; }

        [ScaffoldColumn(false)]
        public int LoginID { get; set; }

        [Required]
        [DisplayName("First Name")]
        public string Firstname { get; set; }

        [Required]
        [DisplayName("First Name")]
        public string Lastname { get; set; }
        [Required]
        public string Email { get; set; }

        [Required]
        [DisplayName("Street Address")]
        public string Streetaddress { get; set; }

        [Required]
        [DisplayName("Birth Date")]
        public System.DateTime Date_of_Birth { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual Login Login { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
    }
}
