//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hearts_of_Gold.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int UserID { get; set; }
        public int LoginID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string Streetaddress { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
    }
}
